definitions:
    alphanumeric:
        type: ["string", "number", "null"]
    numeric:
        type: ["number", "null"]        
    string:
        type: ["string", "null"]
    gender:
        enum: ["male", "female", "mix", "none"]

############################################################################

type: object
additionalProperties: false
properties:
    datetime: 
        type: "string"
        description: "{ eval: \"dateutil.parser.parse\" }"
    sandwich:
        type: "object"
        additionalProperties: false
        properties:
            name:
                $ref: "#/definitions/string"
            type:
                enum: ["Bread1", "Bread2", "Bread3", "Bread4", "Bread5"]
            amount:
                $ref: "#/definitions/numeric"
            detail:
                enum: ["onion", "tomato", "lettuce"]

        
    customer2:
        type: "object"
        additionalProperties: false
        properties:
            name:
                $ref: "#/definitions/string"
            gender:
                $ref: "#/definitions/gender"
            member:
                enum: ["bronze", "silver", "gold", "premium"]

    
    test:
        type: "object"
        additionalProperties: false
        properties:
            type:
                $ref: "#/definitions/string"
            language:
                enum: ["English", "Finnish", "French", "German", "mix", "No_speech", null]
            
    note:
        type: "string"
        $ref: "#/definitions/string"
